RCHECK = {
    0: "Loud and clear.",
    1: "Check.",
    2: "We're online.",
    3: "Copy.",
    4: "We're alive.",
    5: "Aye",
    6: "We hear you.",
    7: "**POWER OVERWHELMING!**",
    8: "We are ready.",
    9: "Awaiting the call.",
    10: "What would you ask of us?",
    11: "We bask in the twilight.",
    12: "We are intrigued.",
    13: "Your demands?",
    14: "Eternal service.",
    15: "We are focused.",
    16: "Our spirit is indomitable.",
    17: "Your thoughts are clear.",
    18: "We heed the call.",
    19: "We feel your presence.",
    20: "Our duty is eternal.",
    21: "Our duty is unending.",
    22: "Glory is eternal.",
    23: "Guide us.",
    24: "Direct us.",
    25: "We await.",
    26: "Reality anchors online.",
    27: "Warp fields online.",
    28: "State thy bidding.",
    29: "You require our skills?",
    30: "We are at full power.",
    31: "Systems at full.",
    32: "Systems online.",
    33: "All systems online.",
    34: "Systems functional.",
    35: "Calibration concluded.",
    36: "Synchronizing.",
    37: "Synchronized.",
    38: "Dimensional strings attuned.",
    39: "Harmonized.",
    40: "Kinetic matrix active.",
    41: "A storm is brewing.",
    42: "By your will!",
    43: "You call upon us?",
    44: "Our thoughts align.",
    45: "Warp field stabilized.",
    46: "We feel your presence.",
    47: "Our expertise is yours.",
    48: "We stand watch.",
    49: "Ever vigilant.",
    50: "*It is a good day to die.*",
    51: "May we be of service?",
    52: "We are the ember of eternity.",
    53: "Give us purpose.",
    54: "Receiving.",
    55: "Awaiting instructions.",
    56: "Standing by.",
    57: "Contact.",
    58: "Oblivion beckons.",
    59: "We await your decree.",
    60: "Loyalty until death.",
    61: "The hour is upon us.",
    62: "Metamorphosis completed.",
    63: "Orders?",
    64: "Yours to command.",
    65: "Your will?",
    66: "Assimilation successful.",
    67: "Awaiting directive.",
    68: "All systems are online and amazing!",
    69: "Systems online! I'm here to kick ass and chew bubblegum, and I have no mouth with which to chew.",
    70: "Sensors are optimal.",
    71: "Listening.",
    72: "Did you miss me?",
    73: "You have our attention.",
    74: "I always did look better in purple!",
    75: "Optics online, let's go kill something!",
    76: "Comm's open.",
    77: "Ready to raise some hell",
    78: "Reporting for action.",
    79: "Ready for service.",
    80: "Comm-link online.",
}

STEPS = {
    0: "There are a bunch of steps, try with `{}step 1`.",
    1: "Have you tried turning it off and on again?",
    2: "Have you tried (re/un)installing it?",
    3: "Have you tried burning it with fire?",
    4: "Have you tried sticking it up your ass?",
    7: "Have you tried chastity, temperance, charity, diligence, patience, kindness and humility?",
    8: "Have you tried? y/n only.",
    9: "Have you tried that in another life?",
    13: "Have you tried hunting things, saving people?",
    18: "Have you tried legally?",
    21: "\N{EAGLE} \N{EAGLE} \N{EAGLE} Have you tried legally? \N{EAGLE} \N{EAGLE} \N{EAGLE}",
    27: "si?",
    26: "\N{EM QUAD}\N{EM QUAD}\N{EM QUAD}",
    34: "Have you tried rubbing one out first?",
    42: "Have you tried finding the answer to the ultimate question of life, the universe, and everything?",
    66: "Have you tried eradication on sight?",
    69: "Have you tried sticking it up your ass multiple times with some company?",
    76: "Have you tried completely fucking up a beloved franchise?",
    99: "Have you tried being the little spoon?",
    100: "Have you tried going To Chicago and Back?",
    232: "Have you tried not causing a nuclear disaster?",
    235: "Have you tried going nuclear?",
    314: "My pet snake is 3.14 meters long. It's a πthon.",
    333: "Have you tried being half-evil?",
    400: "Have you tried making good requests?",
    401: "Have you tried logging in?",
    403: "You're forbidden from trying.",
    404: "Error. Step not found.",
    420: "Have you tried doing it sober?",
    500: "Have you tried configuring it properly?",
    502: "```no valid response```",
    503: "Can't answer you right now. Try later.",
    504: "Have you tried... `loading response`",
    666: "Have you tried selling your soul to Darius?",
    681: "Have you tried forcing the Byzantine Empire to sign a peace treaty?",
    1024: "Have you kilotried?",
    1088: "Have you tried going to university?",
    1337: "0m6 y0u 4 h4x0r pl5 d0n'7 h4ck m3 y0u'll up537 d4r1u5!!!1!!0n3!!1!",
    1492: "Have you tried on another continent?",
    1687: "Have you tried math?",
    1776: "\N{EAGLE} HAVE YOU TRIED FREEDOM? \N{EAGLE}",
    1789: "Have you tried starting a revolution?",
    1848: "Have you tried working harder, comrade?",
    1865: "Have you tried not being racist?",
    1878: "Have you tried being free?",
    1905: "Have you tried looking for general relativity?",
    1912: "Have you tried ordering from China?",
    1914: "Have you tried taking a wrong turn?",
    1922: "Have you tried forming a union of socialist republics?",
    1929: "Have you tried being greatly depressed?",
    1939: "Have you tried invading Poland?",
    1945: "Have you tried invading Poland and suffering the consequences?",
    1957: "Have you tried going into space?",
    1959: "Have you tried using better sillicon chips?",
    1969: "Have you tried making one small step?",
    2020: "Have you tried toilet paper?",
    9001: "OVER 9000?! IT IS TOO POWERFUL!!!!!!",
    186282: "Have you tried going faster than light?", #"1c. In mi/s.",
    299792: "Have you tried going faster than light?", #"1c. In km/s.",
    299792458: "Have you tried going faster than light?", #"1c. In m/s.",
    670616629: "Have you tried going faster than light?", #"1c. In mi/h.",
    1079251200: "Have you tried going faster than light?", #"1c. In km/h.",

}

NOTYET = {
    0: "Nope, doesn't exist.",
    1: "Doesn't exist.",
    2: "There isn't one like that.",
    3: "Nah ¯\_(ツ)_/¯",
    4: "There isn't one like that.",
    5: "Not existing yet.",
    6: "That one doesn't exist.",
    7: "Try something else.",
    8: "Nope.",
}

RULESK = {
    1: "1. Follow Discord's [__Terms of Service__](https://discordapp.com/terms) & [__Guidelines__](https://discordapp.com/terms)",
    2: "2. Avoid excessive spam/copypasta/walls of text and emojis or bullshit like that",
    3: "3. NSFW content is only allowed in marked channels",
    4: "4. No advertising unless allowed by the staff or in the self-promotion section\n\N{HEAVY EXCLAMATION MARK SYMBOL}\N{VARIATION SELECTOR-16} This includes DM advertising",
    5: "5. Don't spam ping or use innapropriate avatars/usernames",
    6: "6. Any excessive swearing, harassment or discriminatory acts are on zero tolerance terms",
    7: "7. Controversial topics such as politics, religion etc are not encouraged",
    }

RULESV = {
    1: "It's your responsibility to read and follow the [__TOS__](https://discordapp.com/terms) & [__guidelines__](https://discordapp.com/guidelines), no exclusions.",
    2: "Even if the channel's name is `spam` don't overdo.",
    3: "Regardless whether it's <#690975135322341487> or not it must not break the [__TOS__](https://discordapp.com/terms) or [__guidelines__](https://discordapp.com/guidelines) mentioned above.",
    4: "If you're interested in advertising whatever contact a staff member first",
    5: "Tagging repeatedly people or roles for whatever reason will be considered spam. Any innapropriate usernames/avatars or impersonating others, especially the staff, will not be tolerated either.",
    6: "Pretty simple. Toxicity, excessions of trolling/spam/drama/flooding/misuse of reactions/racial slurs etc. Don't.",
    7: "They're not forbidden, but if they're being used as a getaways or gateways will be interrupted.",
    }

ALLROLES = {
    1: "Entropy updates",
    2: "Modlogs access",
    3: "#testing pass",
    4: "Adventures",
    5: "Announcements / news",
    6: "Introductions pass",
    7: "DJ",
    8: "Colors pass",
}

ALLROLESDESCR = {
    1: "[<@&632014849320157194>]: Access to channels related to <@492098885649563658>.\n",
    2: "[<@&632194960975724549>]: Access to view all log channels, all changes, kicks, bans and so on.\nWe have nothing to hide.",
    3: "[<@&691003249775476786>]: Access to the <#632014791938015232> channel.\nFor going ham with bot(s).",
    4: "[<@&691003520358547468>]: Access to the Adventures channel.\nThere's a pinned message there with a brief explanation what's it about, if you're feeling curious.",
    5: "[<@&691003435176427600>]: Lets you view the <#690962775400251423> channel.\nWe know not all of you give a rat's ass about those things.",
    6: "[<@&691003518345150494>]: Gives access to the <#633330832647520297> channel.\nTell us about yourself. Or stalk others, we don't care.",
    7: "[<@&691003380675379261>]: The <@&691003380675379261> role gives more permissions to control music being played in voice channels.\n__It's given manually by the staff__.",
    8: "[<@&691003725371932685>]: This role gives you the ability to use `!!colorme change #rrggbb` to change your color.\n__It's given manually by the staff__.",
}